### ISSUE TITLE
Update "Didn't hear from..." mentions after user submits standup

### ISSUE THREAD

**Issue by vabshere** [vipul-sharma20/slack-standup#25]
**Describe the bug**
The "Didn't hear from..." mentions lists out the users who haven't submitted their standup. But after they do, this list should get updated to show who are left.

Solutions:
1. Update the original "Didn't hear from..." message
2. Mention users who submitted late as a reply in the thread

**Comment by vipul-sharma20** [comment]
> Update the original "Didn't hear from..." message

This sounds like a reasonable ask.

> Mention users who submitted late as a reply in the thread

This has been done as a part of: https://github.com/vipul-sharma20/slack-standup/issues/22

**Comment by vabshere** [comment]
> > Mention users who submitted late as a reply in the thread
>
> This has been done as a part of: #22

Let me clarify
I suggested to mention their names as a reply to the "Didn't hear from.." thread to inform teammates of newly submitted standups, as an alternative to updating the message itself.

**Comment by vipul-sharma20** [comment]
Got it. I found the fix I posted to be a decent solution.

Replying on the thread that new post has been added is not going to do much unless it notifies the entire team about it which even the scheduled post doesn't do, it just posts without mentions. Replying to the thread you mentioned would only notify people who were tagged in the message which doesn't help much.

The fix I posted here is more for not keeping stale info on the users who submitted after the scheduled time and not to announce new submissions.
