### ISSUE TITLE
Expose API to access standup info

### ISSUE THREAD

**Issue by Hallicopter** [vipul-sharma20/slack-standup#4]
Want to able to access standup info, so secondary places (like outline) could also ingest the standup logs.

**Comment by vipul-sharma20** [comment]
Yup, that should be a feature to add. an API to get standup logs for a date range (for a specific user or all).

**Comment by vipul-sharma20** [comment]
Pushed API to get standup logs for user/all for date range 9638472a142d0544d6e85594e346db3bcc619267

Doc pending.

**Comment by vipul-sharma20** [comment]
API doc here: [https://documenter.getpostman.com/view/803934/TVYKbwpd](https://documenter.getpostman.com/view/803934/TVYKbwpd)
