### ISSUE TITLE
feature request: Project wise standup

### ISSUE THREAD

**Issue by Hallicopter** [vipul-sharma20/slack-standup#6]
Jacked from something a colleague shared earlier. 

![image](https://user-images.githubusercontent.com/22823026/97279800-747a5280-1861-11eb-8873-7646902f5d5e.png)

**Comment by vipul-sharma20** [comment]
Closing this issue as this feature can be implemented by assigning a user to multiple teams and hence, multiple standups. 

Again, teams can have multiple projects but unfortunately, I think I won't be adding a project wise standup. I would suggest to maybe add teams as projects and implement that.

Documentation pending (for this and various other features added) which I'll cover as a part of https://github.com/vipul-sharma20/slack-standup/issues/14
